/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 BabyBotMat.glb --transform 
Files: BabyBotMat.glb [113.13MB] > /Users/gabriellebaquie/robot/public/models/robot/BabyBotMat-transformed.glb [2.08MB] (98%)
Author: Ceslav Sukstul (https://sketchfab.com/asicson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/babybot-mat-967fe402e33942188b9cf34f8f9be431
Title: BabyBot Mat
*/

import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import { useLayoutEffect, useRef } from "react";

export function Robot(props) {
  const { nodes, materials } = useGLTF(
    "/models/robot/BabyBotMat-transformed.glb"
  );

  const robot = useRef();
  const scroll = useScroll();
  const tl = useRef();

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut" },
    });

    tl.current
      .to(robot.current.rotation, { y: -1 }, 3)
      .to(robot.current.position, { x: 1 }, 3)

      .to(robot.current.rotation, { y: 1 }, 8)
      .to(robot.current.position, { x: -1 }, 8)

      .to(robot.current.rotation, { y: 0 }, 18)
      .to(robot.current.rotation, { x: 1 }, 18)
      .to(robot.current.position, { x: 0 }, 18)

      .to(robot.current.rotation, { y: 0 }, 20)
      .to(robot.current.rotation, { x: 0 }, 20)
      .to(robot.current.position, { x: 0 }, 20)

      .to(robot.current.rotation, { y: 0 }, 22)
      .to(robot.current.rotation, { x: 0 }, 22)
      .to(robot.current.position, { x: 0 }, 22);
  }, []);

  return (
    <group {...props} dispose={null} ref={robot} castShadow>
      <mesh
        castShadow
        geometry={nodes.head_01_Head_0.geometry}
        material={materials["01_Head"]}
        position={[0, 1.464, -0.446]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.137}
      />
      <mesh
        castShadow
        geometry={nodes.base_03_Base_0.geometry}
        material={materials["03_Base"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.479}
      />
      <mesh
        castShadow
        geometry={nodes.body_02_Body_0.geometry}
        material={materials["02_Body"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.479}
      />
    </group>
  );
}

useGLTF.preload("./models/robot/BabyBotMat-transformed.glb");
